Update 2-assembler

diff --git a/0x00-hello_world/2-assembler b/0x00-hello_world/2-assembler
--- a/0x00-hello_world/2-assembler
+++ b/0x00-hello_world/2-assembler
@@ -1,1 +1,8 @@
 
+
+#!/bin/bash
+
+if  $# -le 1 
+then 
+        echo "Error: Give input C file and output assembly file names" 
+        exit 1; 
